export const reviewsData = [
  {
    name: "University of California, Berkeley, USA",
    username: "Sadia Rahman",
    body: "Improved SAT by 200 points through TutorLink's help. Now studying at UC Berkeley with confidence and strong preparation.",
    img: "https://i.postimg.cc/9fQf32YP/6srcd7gz.png",
  },
  {
    name: "North South University",
    username: "Rafiq Hasan",
    body: "Failed calculus twice but succeeded after one-on-one help from TutorLink tutors. Now excelling in engineering.",
    img: "https://i.postimg.cc/nrBFKhnx/istockphoto-1132124550-612x612.jpg",
  },
  {
    name: "BRAC University",
    username: "Nusrat Jahan",
    body: "Mentored by senior Bangladeshi tutors, she became a confident online tutor supporting her family financially.",
    img: "https://i.postimg.cc/qR9BC3VQ/Screenshot-62.png",
  },
  {
    name: "Scholars School & College",
    username: "Arman Hossain",
    body: "With ADHD, Arman improved using visuals and interactive tools in TutorLink sessions. Grades and confidence rose.",
    img: "https://i.postimg.cc/vH5Tf3mn/gettyimages-1441980127-612x612.jpg",
  },
  {
    name: "University of Cape Town, South Africa",
    username: "Mehjabin Akter",
    body: "Writing coaches helped her with essays, interviews, and applications. Now on a full scholarship in South Africa.",
    img: "https://i.postimg.cc/pdcLRSsw/neal-540x540-2022.jpg",
  },
  {
    name: "American International University-Bangladesh",
    username: "Tariq Ahmed",
    body: "Real-world examples and regular sessions made economics easier. GPA increased, and so did his passion for finance.",
    img: "https://i.postimg.cc/vH5Tf3mn/gettyimages-1441980127-612x612.jpg",
  },
  {
    name: "Rajshahi University",
    username: "Shamima Sultana",
    body: "Left teaching job and became a flexible online tutor. Now teaches students from Canada and the UK.",
    img: "https://res.cloudinary.com/dhobkuiqj/image/upload/v1742533054/Sadia%20islam.jpg",
  },
  {
    name: "University of Toronto, Canada",
    username: "Tanvir Alam",
    body: "Received lab-based tutoring from Dhaka professor. That support won him a science scholarship in Canada.",
    img: "https://i.postimg.cc/qR9BC3VQ/Screenshot-62.png",
  },
  {
    name: "Istanbul University, Turkey",
    username: "Sharmin Nahar",
    body: "Prepared for IELTS and interviews with a Bangladeshi tutor. Now interning in Istanbul confidently.",
    img: "https://i.postimg.cc/9fQf32YP/6srcd7gz.png",
  },
  {
    name: "CodersTrust Bangladesh",
    username: "Nazmul Kabir",
    body: "Switched from retail to tech with TutorLink’s coding help. Now working remotely as a junior developer.",
    img: "https://i.postimg.cc/vH5Tf3mn/gettyimages-1441980127-612x612.jpg",
  },
  {
    name: "University of Lahore, Pakistan",
    username: "Fatima Khan",
    body: "Business-based examples helped her grasp statistics. She topped her class and started a consultancy business.",
    img: "https://res.cloudinary.com/dhobkuiqj/image/upload/v1742533054/Sadia%20islam.jpg",
  },
  {
    name: "University of Melbourne, Australia",
    username: "Tomirul Islam",
    body: "Worked full-time while studying. TutorLink helped him master data science and get into graduate school.",
    img: "https://i.postimg.cc/nrBFKhnx/istockphoto-1132124550-612x612.jpg",
  },
  {
    name: "National University of Singapore",
    username: "Ayesha Rahim",
    body: "Improved public speaking skills with online coaching. Now confidently speaks at student events across Asia.",
    img: "https://i.postimg.cc/9fQf32YP/6srcd7gz.png",
  },
  {
    name: "University of Lisbon",
    username: "Carlos Mendes",
    body: "Passed TOEFL after learning academic English from a Bangladeshi tutor. Now in his dream master’s program.",
    img: "https://i.postimg.cc/qR9BC3VQ/Screenshot-62.png",
  },
  {
    name: "Tokyo University",
    username: "Rina Takahashi",
    body: "Writing sessions with a Bangladeshi tutor boosted her confidence. She’s now a nationally recognized writer.",
    img: "https://i.postimg.cc/qR9BC3VQ/Screenshot-62.png",
  },
];
